version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    ports:
      - 3000:3000
    depends_on:
      - phantomjs
    command: ["sh", "-c", "iex -S mix"]
  phantomjs:
    image: wernight/phantomjs
    ports: 
      - 8910:8910
    command: ["phantomjs", "--webdriver=8910"]